-- ADDED
ALTER SESSION SET CONTAINER=XEPDB1;

CREATE TABLESPACE MY_TABLESPACE
    DATAFILE 'tablespace.dbf'
    SIZE 1m;

-- ADDED

CREATE USER LYB IDENTIFIED BY LYB;
GRANT UNLIMITED TABLESPACE TO LYB;
GRANT CREATE SESSIONT TO LYB;
GRANT CONNECT, RESOURCE, DBA TO LYB;

CONNECT LYB/LYB@XEPDB1

CREATE TABLE lyb.t1
(
    id int,
    name varchar2(200)
);

insert into lyb.t1 values (1, 'one'), (2, 'two');